### ISSUE TITLE
ICECAST_MAX_SOURCES not working

### ISSUE THREAD

**Issue by webjazz** [infiniteproject/icecast#4]
Hi,

looks like the parameter ICECAST_MAX_SOURCES is not written to the xml-file.
Or am I missing something?

Regards,

Alex

**Comment by dehy** [comment]
I 👍 this one. I just read the entrypoint.sh script to understand why the ICECAST_MAX_SOURCES wasn't working (default value is 2) and there is nothing handling this variable.

**Comment by infiniteproject** [comment]
> I 👍 this one. I just read the entrypoint.sh script to understand why the ICECAST_MAX_SOURCES wasn't working (default value is 2) and there is nothing handling this variable.

feel free to submit the changes needed to use the variable of your choice.
